language: go
go:
  - 1.2

install:
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.15.zip
  - unzip -q go_appengine_sdk_linux_amd64-1.9.15.zip
  - ./setup.sh

script:
  - ./go_appengine/goapp test ./server/auth
