language: go
go:
  - 1.2

install:
  - export FILE=go_appengine_sdk_linux_amd64-$(curl https://appengine.google.com/api/updatecheck | grep release | grep -o '[0-9\.]*').zip
  - curl -O https://storage.googleapis.com/appengine-sdks/featured/$FILE
  - unzip -q $FILE

script:
  - ./go_appengine/goapp test server/auth
  - ./go_appengine/goapp test server/storage
